/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "simple_constants.h"

namespace rpc {

const simpleConstants g_simple_constants;

simpleConstants::simpleConstants() {
}

} // namespace
