/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef simple_CONSTANTS_H
#define simple_CONSTANTS_H

#include "simple_types.h"

namespace rpc {

class simpleConstants {
 public:
  simpleConstants();

};

extern const simpleConstants g_simple_constants;

} // namespace

#endif
